# ==========================
# 基础配置
# ==========================
set -g mouse on               # 开启鼠标支持
set -g base-index 1           # 窗口编号从 1 开始
setw -g pane-base-index 1     # 面板编号从 1 开始

# ==========================
# 插件管理 (TPM)
# ==========================
# 默认插件
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# 在这里添加你喜欢的其他插件，例如主题：
# set -g @plugin 'catppuccin/tmux'
set -g @plugin 'nordtheme/tmux'

# 初始化 TPM (这行必须在配置文件的最末尾)
run '~/.tmux/plugins/tpm/tpm'
